imports:
    - { resource: tables.yml }
    - { resource: location.yml }

services:
    phpbb.ads.ad.manager:
        class: phpbb\ads\ad\manager
        arguments:
            - '@dbal.conn'
            - '@config'
            - '%phpbb.ads.tables.ads%'
            - '%phpbb.ads.tables.ad_locations%'

    phpbb.ads.banner.banner:
        class: phpbb\ads\banner\banner
        arguments:
            - '@files.upload'
            - '@filesystem'
            - '%core.root_path%'
            - '%phpbb.ads.tables.ad_locations%'

    phpbb.ads.admin.controller:
        class: phpbb\ads\controller\admin_controller
        arguments:
            - '@template'
            - '@language'
            - '@request'
            - '@phpbb.ads.ad.manager'
            - '@config_text'
            - '@config'
            - '@group_helper'
            - '@phpbb.ads.admin.input'
            - '@phpbb.ads.admin.helper'
            - '%core.root_path%'
            - '%core.php_ext%'

    phpbb.ads.admin.helper:
        class: phpbb\ads\controller\admin_helper
        arguments:
            - '@user'
            - '@language'
            - '@template'
            - '@log'
            - '@phpbb.ads.location.manager'
            - '%core.root_path%'
            - '%core.php_ext%'

    phpbb.ads.admin.input:
        class: phpbb\ads\controller\admin_input
        arguments:
            - '@user'
            - '@language'
            - '@request'
            - '@phpbb.ads.banner.banner'

    phpbb.ads.click.controller:
        class: phpbb\ads\controller\click_controller
        arguments:
            - '@phpbb.ads.ad.manager'
            - '@request'

    phpbb.ads.ucp.controller:
        class: phpbb\ads\controller\ucp_controller
        arguments:
            - '@phpbb.ads.ad.manager'
            - '@user'
            - '@language'
            - '@template'
            - '@config'

    phpbb.ads.view.controller:
        class: phpbb\ads\controller\view_controller
        arguments:
            - '@phpbb.ads.ad.manager'
            - '@request'

    phpbb.ads.listener:
        class: phpbb\ads\event\main_listener
        arguments:
            - '@template'
            - '@user'
            - '@config_text'
            - '@config'
            - '@phpbb.ads.ad.manager'
            - '@phpbb.ads.location.manager'
            - '@controller.helper'
        tags:
            - { name: event.listener }
